; string.asm
;
; SPDX-FileCopyrightText: Copyright (C) 2016, 2017, 2020, 2021 Antonio Villena
;
; SPDX-License-Identifier: GPL-3.0-only

; Compatible compilers:
;   SJAsmPlus, <https://github.com/sjasmplus/sjasmplus/>

; 01234567 01234567 01234567 01234567
; abcdefab cdefabcd efabcdef          0642
;    abcde fabcdefa bcdefabc def      3175
        dz      $45
        dz      $45, 'We want to thank all backers'
        dz      $45
        dz      $48, 'AdvanSys'
        dz      $48, 'aguij~n'
        dz      $48, 'Airsoft'
        dz      $48, 'Aivalahostia'
        dz      $48, 'Akis Pluto63 Fletsios'
        dz      $48, 'alberchi'
        dz      $48, 'albor{n70'
        dz      $48, 'aldelgado'
        dz      $48, 'Alejandro Ib{\ez'
        dz      $48, 'Alejandro Valero > wilco2009'
        dz      $48, 'Alfonso Mart}nez > Sr?Presley'
        dz      $48, 'AlfredoLambda'
        dz      $48, 'alioth'
        dz      $48, '[lvaro Adrados'
        dz      $48, 'Alxinho'
        dz      $48, 'Andrew Munro'
        dz      $48, 'AndyRCM'
        dz      $48, 'Antonio Ant',$7f,'nez Rom{n'
        dz      $48, 'Antonio Peregr}n'
        dz      $48, 'Antxiko'
        dz      $48, 'arkapone'
        dz      $48, 'Arnau Jess'
        dz      $48, 'arrizen'
        dz      $48, 'Arturo Arenas Laguna'
        dz      $48, 'Astorri'
        dz      $48, 'AugustoRuiz'
        dz      $48, 'BCH'
        dz      $48, 'Baycorps'
        dz      $48, 'Ben>kenobi'
        dz      $48, 'Brendan Alford'
        dz      $48, 'Broteletal'
        dz      $48, 'Carlos Castre\o'
        dz      $48, 'Carmeloco'
        dz      $48, 'C|sar Moreno L~pez'
        dz      $48, 'chernandezba'
        dz      $48, 'Chernobyl'
        dz      $48, 'ciberchuso'
        dz      $48, 'Ckultur'
        dz      $48, 'dammnield'
        dz      $48, 'Dandare'
        dz      $48, 'Daniel Escudero > Quantumleap'
        dz      $48, 'darro99'
        dz      $48, 'David Bernal Dom}nguez'
        dz      $48, 'David Bl^ck'
        dz      $48, 'David Carri~n > Bytecnia'
        dz      $48, 'David [lvarez Torres'
        dz      $48, 'Deadtool'
        dz      $48, 'Diego Macktek'
        dz      $48, 'Diegols'
        dz      $48, 'DoDesKaDen'
        dz      $48, 'Drachco'
        dz      $48, 'Eduardo Solans'
        dz      $48, 'Eduardo Y{\ez Parareda'
        dz      $48, 'electrotrains'
        dz      $48, 'eltargui'
        dz      $48, 'eltator'
        dz      $48, 'Emilio > modosita68'
        dz      $48, 'Emilio Ortiz'
        dz      $48, 'Eneakao'
        dz      $48, 'Eric Magnus'
        dz      $48, 'Erwin Rattinger'
        dz      $48, 'Esemarcus'
        dz      $48, 'fantastic64'
        dz      $48, 'fastofruto'
        dz      $48, 'Fede Jerez'
        dz      $48, 'Federico J? [lvarez Valero'
        dz      $48, 'Felipe Gamusino'
        dz      $48, 'F|lix Rivero'
        dz      $48, 'Fino de Benej',$7f,'zar'
        dz      $48, 'flopping'
        dz      $48, 'flunky'
        dz      $48, 'Fran Matsusaka'
        dz      $48, 'Francisco Huerta'
        dz      $48, 'Francisco Javier D}az Blanco'
        dz      $48, 'Francisco Javier Nieto'
        dz      $48, 'Francisco L? Vargas'
        dz      $48, 'Fredman'
        dz      $48, 'garvidal'
        dz      $48, 'GUi'
        dz      $48, 'Gacel Miguel'
        dz      $48, 'Garra'
        dz      $48, 'Gazpachuelo'
        dz      $48, 'GroovyDrifter'
        dz      $48, 'Gumpbito'
        dz      $48, 'Gustavo Javier Fern{ndez Sanz'
        dz      $48, 'Hern{n [lvarez'
        dz      $48, '@HoracioGloton'
        dz      $48, 'Hugo Sanch~n'
        dz      $48, 'hyperandroid'
        dz      $48, 'Ignacobo'
        dz      $48, 'I\aki Mart}nez > IMD?guru'
        dz      $48, 'IrregularShed'
        dz      $48, 'Iv{n Ruiz Etxabe'
        dz      $48, 'javidoom'
        dz      $48, 'jgilcas'
        dz      $48, 'JGranadino'
        dz      $48, 'jjmarin'
        dz      $48, 'jmgperez'
        dz      $48, 'JMV'
        dz      $48, 'JSJ'
        dz      $48, 'Javier Albizu'
        dz      $48, 'Javier Basilio'
        dz      $48, 'Javier Ortiz '
        dz      $48, 'Javier Rueda > Blackhero'
        dz      $48, 'Javier S{ez Alonso'
        dz      $48, 'Javier Torres > kowols'
        dz      $48, 'Jean'
        dz      $48, 'Jeff Bennett'
        dz      $48, 'Jes',$7f,'s M'
        dz      $48, 'Jes',$7f,'s Relinque > Pedja'
        dz      $48, 'Jevilon'
        dz      $48, 'Joe Morgan'
        dz      $48, 'Jordi Alabau Basart'
        dz      $48, 'Jordi Mestres Ruiz'
        dz      $48, 'Jordi Ramos'
        dz      $48, 'Jos| Luis Carrasco'
        dz      $48, 'Jose Luis Franzen'
        dz      $48, 'Jos| Manuel Bra\a [lvarez '
        dz      $48, 'Jos| Manuel Cardona'
        dz      $48, 'Jose M{rquez'
        dz      $48, 'Jose Rodelgo > Joss'
        dz      $48, 'Juan Antonio L? Almagro'
        dz      $48, 'Juan Cruz Mangado'
        dz      $48, 'Juan Fco Torres'
        dz      $48, 'Juan Luis Fern{ndez > XurL'
        dz      $48, 'Juan Moreira'
        dz      $48, 'JuanVe'
        dz      $48, 'Juanillo67'
        dz      $48, 'Juanjo > Yog'
        dz      $48, 'Juli{n Garrido'
        dz      $48, 'Julio Mateos'
        dz      $48, 'Julio Medina'
        dz      $48, 'Jungsi'
        dz      $48, 'Kan'
        dz      $48, 'Kelvinator'
        dz      $48, 'Kever67>NL'
        dz      $48, 'Kevin Quinn '
        dz      $48, 'KgMcNeil'
        dz      $48, 'Lenko'
        dz      $48, 'Leticia Vargas Flores'
        dz      $48, 'Lex Sparrow > VZ'
        dz      $48, 'Luis Alberto Gris Casinegro'
        dz      $48, 'Luis Brocan Broky'
        dz      $48, 'Luis I? Garc}a > Benway'
        dz      $48, 'Luis Ruiz'
        dz      $48, 'Luis Soto'
        dz      $48, 'LukeZab > Luca Zabeo'
        dz      $48, 'Mac}as Pajas'
        dz      $48, 'Manu Huertas'
        dz      $48, 'Manu Sevilla'
        dz      $48, 'Manuel Naranjo Vera'
        dz      $48, 'Manuel Sagra de Diego'
        dz      $48, 'mapi20'
        dz      $48, 'MarcusW'
        dz      $48, 'Martin Saguer'
        dz      $48, 'Mejias3D'
        dz      $48, 'melvex'
        dz      $48, 'Metalbrain'
        dz      $48, 'Microhobbit'
        dz      $48, 'microsnk'
        dz      $48, 'Miguel [ngel'
        dz      $48, 'Miguel G? Prada'
        dz      $48, 'Miguel Ser~n'
        dz      $48, 'mike=01'
        dz      $48, 'msch'
        dz      $48, 'Nanoc'
        dz      $48, 'Neil Parsons'
        dz      $48, 'Neuro'
        dz      $48, 'Newsdee'
        dz      $48, 'nivaria'
        dz      $48, 'nonnoes'
        dz      $48, 'Norbert>K?'
        dz      $48, 'nuggetreggae'
        dz      $48, 'Obocaman'
        dz      $48, ']scar BraindeaD'
        dz      $48, ']scar Hern{ndez > Gatuso'
        dz      $48, ']scar Ruiz'
        dz      $48, 'PacMobius'
        dz      $48, 'Pachu003'
        dz      $48, 'Paco Montes'
        dz      $48, 'Pagantipaco'
        dz      $48, 'Pedro Romero'
        dz      $48, 'Peter Robert Jones'
        dz      $48, "Peter 'Sweetlilmre' Edwards"
        dz      $48, 'peterthedark'
        dz      $48, 'princemegahit'
        dz      $48, 'Radastan'
        dz      $48, 'Rafa Vico'
        dz      $48, 'Rafa Zitror'
        dz      $48, 'Raindog'
        dz      $48, 'Ramon Berto'
        dz      $48, 'RetroManiac'
        dz      $48, 'RetroPixeleadores>FloppyDerno'
        dz      $48, 'RetroVirtualMachine'
        dz      $48, 'RetroWorks'
        dz      $48, 'Retrocant'
        dz      $48, 'RiCCo'
        dz      $48, 'Rinconete'
        dz      $48, 'Robcfg'
        dz      $48, 'Robert Perelegre Orteu'
        dz      $48, 'Roberto Henr}quez'
        dz      $48, 'Rub|n Guti|rrez'
        dz      $48, 'Sad1942'
        dz      $48, 'Salvador Perugorria Lorente'
        dz      $48, 'Santiago Romero'
        dz      $48, 'Schombi'
        dz      $48, 'Sebasti{n Tito Rodr}guez'
        dz      $48, 'serbalgi'
        dz      $48, 'Sergio L~pez Cantero'
        dz      $48, 'Sergio S{nchez > RaNaRaMa'
        dz      $48, 'Shikit}n'
        dz      $48, 'sinclair200'
        dz      $48, 'Skywalky'
        dz      $48, 'spark2k06'
        dz      $48, 'SpeedXP'
        dz      $48, 'stcube'
        dz      $48, 'Stratotrasto'
        dz      $48, 'TallerSeverino'
        dz      $48, 'TarkuS666'
        dz      $48, '@TessMSX'
        dz      $48, 'thEpOpE'
        dz      $48, 'TitoxUnix'
        dz      $48, 'Tom Dalby'
        dz      $48, 'Tromponauta'
        dz      $48, 'uniVNG'
        dz      $48, 'Uto'
        dz      $48, 'utopian'
        dz      $48, 'Vago > Avalon Software'
        dz      $48, 'Vejeta'
        dz      $48, 'Vicente Sim~n'
        dz      $48, 'vicenteo'
        dz      $48, 'V}ctor Robledo > Robe=Inie'
        dz      $48, 'vidamia'
        dz      $48, 'Visualtorpedo'
        dz      $48, 'web8bits'
        dz      $48, 'weirdocollector'
        dz      $48, 'Will Woodvine'
        dz      $48, 'Yombo'
        dz      $48, 'Zolt{n B_sz_rm|nyi'
        dz      $48, 'Zup'
        dz      $48
        dz      $43, 'The ZX>UNO core team are'
        dz      $43
        dz      $48, 'Superfo'
        dz      $48, 'antoniovillena'
        dz      $48, 'McLeod'
        dz      $48, 'Quest'
        dz      $48, 'Hark0'
        dz      $48
        dz      $42, 'With additional support from'
        dz      $42
        dz      $48, 'DistWave'
        dz      $48, 'Radastan'
        dz      $48, 'jepalza'
        dz      $48, 'Mejias3D'
        dz      $48, 'chernandezba'
        dz      $48, 'Anyone We Forgot???'
        dz      $48
        dz      $44, 'Easter egg credits'
        dz      $44
        dz      $48, 'Coder: Antonio Villena'
        dz      $48, 'Music: Yerzmyey'
        dz      $48, 'Graphics: Quest'
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        dz      $48
        defb    1
