# sdcc.inc.mk - script to download and build SDCC.
#
# This file is a part of main Makefile.
#
# SPDX-FileCopyrightText: 2021 Ivan Tatarinov <ivan-tat@ya.ru>
#
# SPDX-License-Identifier: GPL-3.0-or-later

.downloads/sdcc:
	mkdir -p $@

.PHONY: $(foreach t,build install uninstall clean distclean,$(t)-sdcc)

ifeq ($(_DoBuild),1)

SDCC_ARCHIVE		= .downloads/sdcc/sdcc-src-4.1.0.tar.bz2
SDCC_ARCHIVE_SHA256	= 81edf776d5a2dc61a4b5c3408929db7b25874d69c46e4a71b116be1322fd533f
SDCC_ARCHIVE_TYPE	= .tar.bz2
SDCC_ARCHIVE_SUBDIR	= sdcc

.downloads/sdcc/sdcc-src-4.1.0.tar.bz2: | .downloads/sdcc
	wget -c https://sourceforge.net/projects/sdcc/files/sdcc/4.1.0/$(@F)/download -O $@

sdcc/.extracted: $(SDCC_ARCHIVE)
	rm -rf $(@D)
	extract.sh $<\
	 --sha256 $(SDCC_ARCHIVE_SHA256)\
	 --type $(SDCC_ARCHIVE_TYPE)\
	 --subdir $(SDCC_ARCHIVE_SUBDIR)\
	 --output $(@D)
	touch $@

build-sdcc: | sdcc/.extracted sdcc.mk
	$(MAKE) -w -C sdcc -f ../sdcc.mk

install-sdcc: | sdcc/.extracted sdcc.mk
	$(MAKE) -w -C sdcc -f ../sdcc.mk prefix=$(SDCCHOME) install

 ifeq ($(_DoClean),1)

uninstall-sdcc: | sdcc/.extracted sdcc.mk
	$(MAKE) -w -C sdcc -f ../sdcc.mk prefix=$(SDCCHOME) uninstall

clean-sdcc: | sdcc/.extracted sdcc.mk
	$(MAKE) -w -C sdcc -f ../sdcc.mk clean

distclean-sdcc:
	rm -rf sdcc

 else	#  !_DoClean

uninstall-sdcc\
clean-sdcc\
distclean-sdcc:;

 endif	#  !_DoClean

endif	# _DoBuild

ifeq ($(_UsePrecompiledOnWindows),1)

SDCC_ARCHIVE		= .downloads/sdcc/sdcc-4.1.0-setup.exe
SDCC_ARCHIVE_SHA256	= cbf064c9f1a3f9a73db6d2c8ba3a43563fa3a2d2966f52cf5a571a3064222ed8
SDCC_ARCHIVE_TYPE	= .7z
SDCC_ARCHIVE_SUBDIR	= .

SDCC_SUBDIRS=\
 bin\
 doc\
 include\
 lib\
 non-free

.downloads/sdcc/sdcc-4.1.0-setup.exe: | .downloads/sdcc
	wget -c https://sourceforge.net/projects/sdcc/files/sdcc-win32/4.1.0/$(@F)/download -O $@

sdcc/.extracted: $(SDCC_ARCHIVE)
	rm -rf $(@D)
	extract.sh $<\
	 --sha256 $(SDCC_ARCHIVE_SHA256)\
	 --type $(SDCC_ARCHIVE_TYPE)\
	 --subdir $(SDCC_ARCHIVE_SUBDIR)\
	 --output $(@D)
	touch $@

build-sdcc: sdcc/.extracted

install-sdcc: | sdcc/.extracted
	cd sdcc;\
	{ echo '# This file was automatically generated by Make.';\
	echo '.PHONY: install';\
	echo 'install:\';\
	find $(SDCC_SUBDIRS) -type f\
	| sed -Ee 's,(.+), $$(DEST)$$(prefix)/\1\\,';\
	echo '';\
	find $(SDCC_SUBDIRS) -type d\
	| sed -Ee 's,(.+),$$(prefix)/\1\\,';\
	echo -e ':\n\tmkdir -p $$@';\
	for d in $(SDCC_SUBDIRS); do\
		if [ $$d = bin ]; then\
			find $$d -type f\
			| awk '{print gensub(/^(.+)\/([^/]+)/, "$$(DEST)$$(prefix)/\\1/\\2: \\1/\\2 | $$(DEST)$$(prefix)/\\1\n\t$$(INSTALL_PROGRAM) -m 755 $$< $$@", "g")}';\
		else\
			find $$d -type f\
			| awk '{print gensub(/^(.+)\/([^/]+)/, "$$(DEST)$$(prefix)/\\1/\\2: \\1/\\2 | $$(DEST)$$(prefix)/\\1\n\t$$(INSTALL) -m 644 $$< $$@", "g")}';\
		fi;\
	done; } >install.mk;\
	$(MAKE) -w -f install.mk DEST=$(DEST) prefix=$(prefix) INSTALL=$(INSTALL) INSTALL_PROGRAM=$(INSTALL_PROGRAM) install

 ifeq ($(_DoClean),1)

uninstall-sdcc:
	test '$(SDCCHOME)' = . || rm -rf $(SDCCHOME)

clean-sdcc\
distclean-sdcc:
	rm -rf sdcc

 else	#  !_DoClean

uninstall-sdcc\
clean-sdcc\
distclean-sdcc:;

 endif	#  !_DoClean

endif	# _UsePrecompiledOnWindows
