# therighttools.inc.mk - script to download and build The Right Tools.
#
# This file is a part of main Makefile.
#
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: 2022 Ivan Tatarinov
# SPDX-License-Identifier: GPL-3.0-or-later

$(DOWNLOADS)/therighttools \
therighttools:
	mkdir -p $@

.PHONY: $(foreach t,build install uninstall clean distclean,$(t)-therighttools)

ifeq ($(_DoBuild),1)

ifeq ($(USE_THERIGHTTOOLS_VERSION),0.2)
 THERIGHTTOOLS_ARCHIVE		= therighttools-v0.2.tar.bz2
 THERIGHTTOOLS_ARCHIVE_URL	= https://gitlab.com/ivan-tat/therighttools/-/archive/v0.2/$(THERIGHTTOOLS_ARCHIVE)
 THERIGHTTOOLS_ARCHIVE_SHA256	= e1cf2e9a33278f94b844ccfa3abc0e0a8bc3182a3d0d4fb22bcc5783cd17c175
 THERIGHTTOOLS_ARCHIVE_TYPE	= .tar.bz2
 THERIGHTTOOLS_ARCHIVE_SUBDIR	= therighttools-v0.2
else ifeq ($(USE_THERIGHTTOOLS_VERSION),0.2.1)
 THERIGHTTOOLS_ARCHIVE		= therighttools-v0.2.1.tar.bz2
 THERIGHTTOOLS_ARCHIVE_URL	= https://gitlab.com/ivan-tat/therighttools/-/archive/v0.2.1/$(THERIGHTTOOLS_ARCHIVE)
 THERIGHTTOOLS_ARCHIVE_SHA256	= b03a97edcf4346c74f45c04b3b6f434f56e7c11c110ecd3c1e63eab6c7ce0831
 THERIGHTTOOLS_ARCHIVE_TYPE	= .tar.bz2
 THERIGHTTOOLS_ARCHIVE_SUBDIR	= therighttools-v0.2.1
else
 $(error Unknown The Right Tools version: "$(USE_THERIGHTTOOLS_VERSION)")
endif

$(DOWNLOADS)/therighttools/$(THERIGHTTOOLS_ARCHIVE): | $(DOWNLOADS)/therighttools
	wget -c $(THERIGHTTOOLS_ARCHIVE_URL) -O $@

therighttools/.extracted: $(DOWNLOADS)/therighttools/$(THERIGHTTOOLS_ARCHIVE)
	$(RM) -r $(@D)
	extract.sh $<\
	 --sha256 $(THERIGHTTOOLS_ARCHIVE_SHA256)\
	 --type $(THERIGHTTOOLS_ARCHIVE_TYPE)\
	 --subdir $(THERIGHTTOOLS_ARCHIVE_SUBDIR)\
	 --output $(@D)
	touch $@

build-therighttools: | therighttools/.extracted therighttools.mk
	$(MAKE) -w -C therighttools -f ../therighttools.mk

install-therighttools: | therighttools/.extracted therighttools.mk
	$(MAKE) -w -C therighttools -f ../therighttools.mk prefix=$(shell realpath -m --relative-to=therighttools $(prefix)) install

uninstall-therighttools: | therighttools.mk
	test -d therighttools && $(MAKE) -w -C therighttools -f ../therighttools.mk prefix=$(shell realpath -m --relative-to=therighttools $(prefix)) uninstall

ifeq ($(_DoClean),1)

clean-therighttools: | therighttools.mk
	if test -f therighttools/.extracted; then $(MAKE) -w -C therighttools -f ../$| clean; fi

else	#  !_DoClean

clean-therighttools:;

endif	#  !_DoClean
endif	# _DoBuild

ifeq ($(_UsePrecompiledOnWindows),1)

ifeq ($(PROCESSOR_ARCHITECTURE),X86)
else ifeq ($(PROCESSOR_ARCHITECTURE),AMD64)
else ifeq ($(PROCESSOR_ARCHITECTURE),EM64T)
else
 $(warning Unsupported processor architecture: "$(PROCESSOR_ARCHITECTURE)")
endif

ifeq ($(USE_THERIGHTTOOLS_VERSION),0.2)
 THERIGHTTOOLS_ARCHIVE		= therighttools-0.2-windows-i686.zip
 THERIGHTTOOLS_ARCHIVE_URL	= https://gitlab.com/ivan-tat/therighttools/uploads/10bd40aace7a950d36e7105cada6f5e7/$(THERIGHTTOOLS_ARCHIVE)
 THERIGHTTOOLS_ARCHIVE_SHA256	= 1c80b4dad8ec8bb5a5acb1d8afee2205c326046233482b5b7bae6d8152eb54c5
 THERIGHTTOOLS_ARCHIVE_TYPE	= .zip
 THERIGHTTOOLS_ARCHIVE_SUBDIR	=
 THERIGHTTOOLS_SUBDIRS		= bin
else ifeq ($(USE_THERIGHTTOOLS_VERSION),0.2.1)
 THERIGHTTOOLS_ARCHIVE		= therighttools-0.2.1-windows-i686.zip
 THERIGHTTOOLS_ARCHIVE_URL	= https://gitlab.com/ivan-tat/therighttools/uploads/b42ce1a3a05d77017d34f9277cd0352b/$(THERIGHTTOOLS_ARCHIVE)
 THERIGHTTOOLS_ARCHIVE_SHA256	= a604ecf55f8ab4ea75f95428a150a8e17aaed276ab439d07ebe7348f78055f92
 THERIGHTTOOLS_ARCHIVE_TYPE	= .zip
 THERIGHTTOOLS_ARCHIVE_SUBDIR	=
 THERIGHTTOOLS_SUBDIRS		= bin
else
 $(error Unknown The Right Tools version: "$(USE_THERIGHTTOOLS_VERSION)")
endif

$(DOWNLOADS)/therighttools/$(THERIGHTTOOLS_ARCHIVE): | $(DOWNLOADS)/therighttools
	wget -c $(THERIGHTTOOLS_ARCHIVE_URL) -O $@

therighttools/.extracted: $(DOWNLOADS)/therighttools/$(THERIGHTTOOLS_ARCHIVE)
	$(RM) -r $(@D)
	extract.sh $<\
	 --sha256 $(THERIGHTTOOLS_ARCHIVE_SHA256)\
	 --type $(THERIGHTTOOLS_ARCHIVE_TYPE)\
	 $(if $(THERIGHTTOOLS_ARCHIVE_SUBDIR),--subdir $(THERIGHTTOOLS_ARCHIVE_SUBDIR))\
	 --output $(@D)
	cd $(@D);\
	{ echo '# This file was automatically generated by Make.';\
	echo '.PHONY: install';\
	echo 'install:\';\
	find $(THERIGHTTOOLS_SUBDIRS) -type f | sed -Ee 's,(.+), $$(DESTDIR)$$(prefix)/\1\\,';\
	echo '';\
	find $(THERIGHTTOOLS_SUBDIRS) -type d | sed -Ee 's,(.+),$$(DESTDIR)$$(prefix)/\1 \\,';\
	printf ':\n\tmkdir -p $$@\n';\
	for d in $(THERIGHTTOOLS_SUBDIRS); do\
		if [ $$d = bin ]; then\
			find $$d -type f | sed -Ee 's,^(.+)/([^/]+),$$(DESTDIR)$$(prefix)/\1/\2: \1/\2 | $$(DESTDIR)$$(prefix)/\1\n\t$$(INSTALL_PROGRAM) $$< $$@,';\
		else\
			find $$d -type f | sed -Ee 's,^(.+)/([^/]+),$$(DESTDIR)$$(prefix)/\1/\2: \1/\2 | $$(DESTDIR)$$(prefix)/\1\n\t$$(INSTALL_DATA) $$< $$@,';\
		fi;\
	done;\
	echo '.PHONY: uninstall';\
	echo 'uninstall:';\
	find $(THERIGHTTOOLS_SUBDIRS) -type f | sed -Ee 's,(.+),\t$$(RM) $$(DESTDIR)$$(prefix)/\1,';\
	} >Makefile
	touch $@

build-therighttools: | therighttools/.extracted

install-therighttools: | therighttools/.extracted
	$(MAKE) -w -C therighttools\
	 DESTDIR=\
	 prefix=$(shell realpath -m --relative-to=therighttools $(prefix))\
	 INSTALL_PROGRAM='$(INSTALL) -m 755'\
	 INSTALL_DATA='$(INSTALL) -m 644'\
	 install

uninstall-therighttools:
	$(MAKE) -w -C therighttools\
	 DESTDIR=\
	 prefix=$(shell realpath -m --relative-to=therighttools $(prefix))\
	 uninstall

ifeq ($(_DoClean),1)

clean-therighttools:;

else	#  !_DoClean

clean-therighttools:;

endif	#  !_DoClean
endif	# _UsePrecompiledOnWindows

ifeq ($(_DoClean),1)

distclean-therighttools:
	$(RM) -r $(DOWNLOADS)/therighttools therighttools

else	# !_DoClean

distclean-therighttools:;

endif	# !_DoClean
